### ISSUE TITLE
Kargo Alıcı Ödemeli hk.

### ISSUE THREAD

**Issue by unlufurkan** [emreakdas/shopier-payment#4]
Merhaba, test ettim herhangi bir sorun yok fakat ben bu işlem sonucunda Shopier'dan kargo kodu almak istediğimde sipariş alıcı ödemeli olarak gittiği için vermiyor. Satıcı ödemeli olarak bu işlemi gerçekleştirtmek için hangi ayarı değiştirmek gerek veya mümkün mü?

**Comment by emreakdas** [comment]
Hayır, maalesef öyle bir ayar bulunmamaktadır.
