### ISSUE TITLE
payment response

### ISSUE THREAD

**Issue by LuckyPaster** [emreakdas/shopier-payment#5]
**shopier'da geri dönüş sayfasını shopiernotify yaptım fakat hala geri dönerken herhangi bir post gelmiyor ve true yada false işlevini görmüyor
çok yerden yapmayı denedim fakat bir türlü yapamadım size instagramdan vs ulaşmaya çalıştım fakat bakmadınız
burdan yardımcı olabilirseniz ne mutlu bana iyi günler..**

**Comment by emreakdas** [comment]
Shopier'a callback tanımladınız mı?

**Comment by emreakdas** [comment]
eğer hala çözemediyseniz tekrardan ulaşınız şimdilik kapatıyorum.

**Comment by LuckyPaster** [comment]
> Shopier'a callback tanımladınız mı?

evet tanımladım ödeme sonrası sayfaya atıyor fakat true yada false dönmüyor

**Comment by emreakdas** [comment]
true veya false dönmesini zaten tanımlamadık. shopierNotify sayfasını güncelliyorum böyle bir deneyin ve öyle kendiniz aksiyon alın.

**Comment by LuckyPaster** [comment]
> true veya false dönmesini zaten tanımlamadık. shopierNotify sayfasını güncelliyorum böyle bir deneyin ve öyle kendiniz aksiyon alın.

vaktinizi aldım özür dilerim aslında istediğim satın aldıktan sonra eğer user giriş yapılı ise
üyeliğine 30 gün eklemesi

**Comment by LuckyPaster** [comment]
> true veya false dönmesini zaten tanımlamadık. shopierNotify sayfasını güncelliyorum böyle bir deneyin ve öyle kendiniz aksiyon alın.

bu şekilde deneyip hemen yazıcam

**Comment by LuckyPaster** [comment]
`$expected = hash_hmac('SHA256', $data, $shopierSecret, true);`
burada `$shopierSecret`'ı nerden çektiğini gerçekten anlayamadım
shopier API'ı tanımlamammı gerekiyor?

**Comment by emreakdas** [comment]
expected değişkeni shopierden gelen bilgilere göre hash oluşturur ve ona göre eşleştirilir. hash_hmac kullanımında shopierSecret bir yerden çekilmiyor. kullanmak isterseniz shopierSecret değişkeni ile bu anahtarı kullanabilirsiniz.

sizin yapacağınız tek şey shopierNotify sayfasında işlem başarılı ise yapacaklarınız kısmında üye giriş yapmış mı yapmamış mı onun kontrolü ve bakiye eklemek sipariş id'sine göre.
